const path = require('path')
exports.log = require('./log')
exports.Handlers = require('./handlers')
exports.COMMAND_DIR = path.join(__dirname, './commands/')
exports.constants = require('./config/constants')
